# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signupuse',
            new_name='Signupuser',
        ),
    ]
